In [1]:
import numpy as np
import pandas as pd

In [23]:
column_names = ['speed1','speed2','point','rating','size1','size2','pred']

In [30]:
df = pd.read_csv('car_evaluation.csv', header=None, names=column_names, usecols=['speed1','size1','pred'])

In [31]:
df.sample(9)

speed1  size1   pred
115   vhigh    big  unacc
899     med    big  unacc
754    high    big    acc
0     vhigh  small  unacc
1215    med  small  unacc
1503    low  small  unacc
210   vhigh    med  unacc
1356    low    big  unacc
727    high    big    acc

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop('pred',axis=1),
                                                    df['pred'], 
                                                    test_size=0.2,
                                                    random_state=42)
X_train.shape, X_test.shape

((1382, 2), (346, 2))

In [33]:
from sklearn.preprocessing import OrdinalEncoder

In [34]:
oe = OrdinalEncoder(categories=[['low','med','high','vhigh'],['small','med','big']])

In [35]:
oe.fit(X_train)

OrdinalEncoder(categories=[['low', 'med', 'high', 'vhigh'],
                           ['small', 'med', 'big']])

In [36]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [37]:
X_train

array([[3., 2.],
       [1., 0.],
       [0., 2.],
       ...,
       [2., 1.],
       [0., 0.],
       [1., 0.]])

In [38]:
oe.categories_

[array(['low', 'med', 'high', 'vhigh'], dtype=object),
 array(['small', 'med', 'big'], dtype=object)]

In [39]:
from sklearn.preprocessing import LabelEncoder

In [40]:
le = LabelEncoder()

In [41]:
le.fit(y_train)

LabelEncoder()

In [43]:
le.classes_

array(['acc', 'good', 'unacc', 'vgood'], dtype=object)

In [44]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [47]:
y_train.shape

(1382,)

In [48]:
y_train

array([2, 2, 2, ..., 0, 2, 0])

In [46]:
y_test

array([2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 3, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0,
       0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 1, 2, 2, 2, 2, 2, 0, 0,
       0, 3, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 2, 0, 3,
       2, 0, 0, 2, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 3, 2, 2, 0, 3, 0, 2, 0,
       3, 0, 2, 1, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 1, 0, 2, 2, 0,
       2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2,
       0, 2, 2, 0, 2, 3, 2, 2, 2, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 3, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0, 3, 0, 2, 0, 2, 2, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0,
       2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0,
       3, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2,
       2, 2, 0, 3, 2, 2, 2, 0, 2, 2, 3, 2, 2, 0, 0, 2, 0, 2, 0, 0, 2, 2,
       0, 1, 3, 0, 0, 2, 2, 2, 2, 3, 0, 0, 2, 2, 2,